{{- if eq .Values.scope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-collector-coltroller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-collector-coltroller
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-collector-coltroller
  namespace: {{ .Release.Namespace }}
{{- end}}
